### Criação de Leilão
POST http://localhost:8080/auction HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
  "product_name":"PROD1",
  "category": "CAT1",
  "description": "Essa é uma boa descrição para o produto 1",
  "condition": 2
}

### Buscar Leilões Ativos
GET http://localhost:8080/auction?status=0
Host: localhost:8080
Content-Type: application/json

### Buscar Leilões Inativos
GET http://localhost:8080/auction?status=0
Host: localhost:8080
Content-Type: application/json
